source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'iOS-Check-Permission_Example', :exclusive => true do
  pod "iOS-Check-Permission", :path => "../"
end

target 'iOS-Check-Permission_Tests', :exclusive => true do
  pod "iOS-Check-Permission", :path => "../"

  
end
